eureka: 
  client: 
    enbaled: true
logging: 
  level: 
    ROOT: info
zhb: 
  forever:
    msg: 
      url: http://localhost:8012
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/zhb_springcloud
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 3000
    minIdle: 1


    
    
  