server:
  port: 8761
  tomcat:
      uri-encoding: UTF-8
spring:
  application:
    name: eureka
  profiles:
    active: dev
logging:
  level:
    ROOT: info
    com.forever: debug
  file:
    log/eureka.log		
  