server: 
  port: 8012
  tomcat: 
      uri-encoding: UTF-8
spring: 
  application: 
    name: ms
  profiles: 
    active: dev
logging: 
  level: 
    ROOT: info
  file: 
    log/ms.log		
  